### ISSUE TITLE
Please include list of available includes in cdn main page

### ISSUE THREAD

**Issue by ylluminarious** [opal/opal-cdn#1]
Please put a list of files we can use from https://github.com/opal/opal-cdn/tree/gh-pages/opal/current at http://cdn.opalrb.org/.

**Comment by ylluminarious** [comment]
I think including `opal-jquery` and `opal-browser` and any other core opal libs would also be useful for easy inclusion.

**Comment by ggrossetie** [comment]
I just saw that the index page is broken with v0.8.0.rc2 (current version): http://cdn.opalrb.org/
If I add the following JavaScript:

``` javascript
<script>
  Opal.load('opal-parser');
</script>
```

I can see `Hello from the console!` in the console but then I get:

```
Uncaught NoMethodError: undefined method `[]' for nil(anonymous function) 
@ opal.js:3607Opal.defn.TMP_1 
@ opal.js:2486method_missing_stub @ opal.js:722(anonymous function) 
@ VM158:9(anonymous function) 
@ VM158:10(anonymous function) 
@ opal-parser.js:13380run_ruby_scripts 
@ opal-parser.js:13413
```

**Comment by ggrossetie** [comment]
I also need to load `Opal.load('native');`
