### ISSUE TITLE
Consider compiling without the need to load/require modules

### ISSUE THREAD

**Issue by elia** [opal/opal-cdn#14]
_[from gitter](https://gitter.im/opal/opal?at=55e84ab017b2081605a58756)_

> `@bigtunacan` you can have `<script type=“text/ruby”>`, but you need to require add opal-parser.js
> `@bigtunacan` https://github.com/opal/opal/issues/239#issuecomment-17218373
> **bigtunacan Sep 03 15:36**
> Ok; so I tried running this basic example
> 
> ```
> <!DOCTYPE html>
> <html>
> <head>
> <script src="opal.min.js"></script>
> <script src="opal-parser.min.js"></script>
> 
> <script type=“text/ruby”>
> alert "hi"
> </script>
> </head>
> <body>
> </body>
> </html>
> ```
> 
> It doesn't get any errors, but nothing happens.
> Shouldn't that give me an alert popup?
> **gabrielrios Sep 03 15:51**
> `@bigtunacan` missing one step, you need to load the parser
> 
> ```
> <!DOCTYPE html>
> <html>
>     <head>
>         <script src="http://cdn.opalrb.org/opal/current/opal.js"></script>
>         <script src="http://cdn.opalrb.org/opal/current/opal-parser.js"></script>
>         <script type="text/javascript">Opal.load('opal-parser')</script>
>         <script type="text/ruby">
>             puts "hi"
>         </script>
>     </head>
>     <body>
>     </body>
> </html>
> ```
> 
> **bigtunacan Sep 03 15:56**
> Ok; now I'm in business
> Thank you!

This happens a lot, so I was wondering if it wouldn't be better to compile them so that they run directly

@Mogztter thoughts?

**Comment by ggrossetie** [comment]
You mean loading automatically the module (i.e. append `Opal.load('opal-parser')` at the end of the script) ?

We are doing similar thing in Asciidoctor.js to avoid the extra line `Opal.load('asciidoctor');`
Maybe Opal should provide an option to automatically load modules ?

**Comment by elia** [comment]
Yes, that's what I meant. Should be as easy as changing the dist rake task.

**Comment by ggrossetie** [comment]
> Yes, that's what I meant. Should be as easy as changing the dist rake task.

@elia You want to do the change in Opal core or here ?

**Comment by elia** [comment]
@Mogztter just here, maybe I'll add a different sub-extension for pre-required files (or vice-versa)

> ostruct.requireable.js / ostruct.js

vs.

> ostruct.required.js / ostruct.js

**Comment by ggrossetie** [comment]
OK, as long as you keep both I'm fine with this change 😊
I think it's a good practice to *not* eagerly load JavaScript code but at the same time it easier to get started if we do.

I believe the sub-extension should be for pre-required files... but it's a tough choice!

`opal.loaded.js / opal.js` (fully loaded and ready for action!)

**Comment by elia** [comment]
I added examples of the `<script>` tag with an onload attribute that should work fine, seems a good compromise for now.
