### ISSUE TITLE
Publish versions on cdnjs

### ISSUE THREAD

**Issue by ggrossetie** [opal/opal-cdn#19]
It might be a good idea to "cross-publish" versions on http://cdn.opalrb.org/ and https://cdnjs.com/
The latest version on cdnjs is 0.3.43: https://cdnjs.com/libraries/opal

**Comment by elia** [comment]
Go for it, I stopped doing that because the process was too cumbersome (i.e. Sending a PR and waiting for their approval) but maybe things are better off now

**Comment by elia** [comment]
Closing this, CDNJS doesn't seem to be in great shape and as said the PR process has too drag, our CDN domain should be good and fast as it's backed by CloudFlare 🚀

**Comment by ggrossetie** [comment]
I wholeheartedly agree 😞
