### ISSUE TITLE
CDN does not support SSL

### ISSUE THREAD

**Issue by dan42** [opal/opal-cdn#25]
Doesn't work: https://cdn.opalrb.org/opal/current/opal.js

Which is kind of a big deal nowadays

**Comment by ggrossetie** [comment]
I don't have access to the configuration but I think it's possible: https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by elia** [comment]
@dan42 @Mogztter GitHub's instructions would only work for the github.io subdomain. I'm planning to move everything under opalrb.com for which I have full access and enable SSL via CloudFlare.

**Comment by ggrossetie** [comment]
@elia Roger that ! 👌

**Comment by elia** [comment]
So, we now have https://cdn.opalrb.com up and running (finally!)

**Comment by ggrossetie** [comment]
Neat 👌
