### ISSUE TITLE
Top page URL is invalid

### ISSUE THREAD

**Issue by ongaeshi** [opal/opal-cdn#31]
http://cdn.opalrb.org -> http://cdn.opalrb.com

**Comment by ggrossetie** [comment]
Thanks for the notice @ongaeshi 
You mean on GitHub right ? Or did you find this URL elsewhere ?

I can't edit this URL myself :disappointed: 


Ping @elia

**Comment by elia** [comment]
Thanks so much! Fixed ✅

**Comment by ongaeshi** [comment]
Thanks @Mogztter! Yes, GitHub URL.
Thanks @elia!
