### ISSUE TITLE
Missing opal-cdn/opa/0.11.4

### ISSUE THREAD

**Issue by nwtgck** [opal/opal-cdn#32]
Hi, developers. Thank you very much for a great project!

I think `opal-cdn/opa/0.11.4` is missing now. Although `opal-cdn/opa/current` is v0.11.4, there is no `opal-cdn/opa/0.11.4`. I think this that it is easy to copy :D

**Comment by elia** [comment]
Added (finally! 😅), although gh-pages is still being updated…
