### ISSUE TITLE
Publish version 1.0.0 on the CDN

### ISSUE THREAD

**Issue by ggrossetie** [opal/opal-cdn#34]
- https://rubygems.org/gems/opal/versions/1.0.0
- https://github.com/opal/opal/releases/tag/v1.0.0

**Comment by elia** [comment]
The best solution for this would be to devise a GitHub action that updates the CDN at each push (for master) and for every tag.

**Comment by elia** [comment]
Added (finally! 😅), although gh-pages is still being updated…
