### ISSUE TITLE
Error calling Opal

### ISSUE THREAD

**Issue by jeezs** [opal/opal-cdn#35]
When adding Opal using the following <script src="opal.js" onload="Opal.require('opal')"></script>
there's an "LoadError: cannot load such file -- opal" error.

**Comment by elia** [comment]
You're right, we should update the generated code to add `Opal.loaded(['opal'])` as the last instruction just for Opal, or remove [the exception](https://github.com/opal/opal/blob/f1c093bb946af78403971151ec5fa12b086c6f76/tasks/building.rake#L36) that autoloads it.

**Comment by bolandross** [comment]
Hey folks,

I am still getting this error in Safari. Are there instructions on what to do to avoid it?

**Comment by bolandross** [comment]
Hey, more than a year has passed. Any news on this issue?

I'd love to follow the first steps demo code in the project readme, but all I'm getting in Safari is:

`LoadError: cannot load such file -- opal`

**Comment by hmdne** [comment]
This all should work now. We now never recommend to Opal.load('opal'). Ref: opal/opal#2300
