### ISSUE TITLE
Create the 0.7.0 and 0.7.1 tags

### ISSUE THREAD

**Issue by ggrossetie** [opal/opal-cdn#5]
@elia Could you please create the v0.7.0 and v0.7.1 ? I want to use bower to update my dependency.

Thanks

**Comment by ggrossetie** [comment]
I think we also need to update the `current` directory in each tag to use the corresponding version.

**Comment by elia** [comment]
@Mogztter not finding the time to do the thing I did better and added you as a collaborator on opal-cdn ;)

**Comment by ggrossetie** [comment]
Ouh nice, thanks! @elia
